import type {Metadata} from "next";

import "./globals.css";
import {ThemeProvider} from "@/components/ThemeProvider";
import {Header} from "@/components/Header";

export const metadata: Metadata = {
  title: "countries-app",
  description: "Generated by appncy",
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider
          disableTransitionOnChange
          enableSystem
          attribute="class"
          defaultTheme="system"
        >
          <div className="grid min-h-svh grid-rows-[auto,1fr,auto] bg-background font-sans antialiased">
            <Header />
            <main className="container py-4 md:py-8">{children}</main>
            <footer className="text-center leading-[4rem] opacity-70">
              © {new Date().getFullYear()} countries-app
            </footer>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
